apiVersion: v1
kind: Service
metadata:
    name: "workshopsday2aks-8196"
    labels:
        app: "workshopsday2aks-8196"
spec:
    type: LoadBalancer
    ports:
    - port: 8082
      targetPort: 8082
      protocol: TCP
      name: http
    selector:
        app: "workshopsday2aks-8196"