apiVersion: v1
kind: Service
metadata:
    name: "workshopsday2aks-04d8"
    labels:
        app: "workshopsday2aks-04d8"
spec:
    type: LoadBalancer
    ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
      name: http
    selector:
        app: "workshopsday2aks-04d8"